# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e271257d39123de32e2d1eba16086bb7ef780686b971d1aa69fbe29124c97b5f012e688306aae413ac9f3cd065b15b173edd6054221f3e31fa2799c415b436e3

test:
  secret_key_base: e25f14768643c1370ea3c72483d40bebeb984766f8618537c985c760832d688fdded8f19b915a810f7cab52c721bac40ea637a6258412186b44252d97adee9b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
